/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmpresaPanel.java
 *
 * Created on 12-feb-2010, 2:19:53
 */

package ingenias.jade.components;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;

/**
 *
 * @author Victor
 */
public class EmpresaPanel extends javax.swing.JPanel {

    DecimalFormat df = new DecimalFormat("0.0000");
    VentanaGrafica ventana;
    Vector precio,volumen,fecha;
    String empresa;
    /** Creates new form EmpresaPanel */
    public EmpresaPanel(String empresa) {
        initComponents();

        this.empresa = empresa;
        precio = new Vector();
        volumen = new Vector();
        fecha = new Vector();

        ventana = VentanaGrafica.start(empresa,precio,volumen,fecha);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numAcciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorAccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        btnGraficas = new javax.swing.JButton();

        jLabel1.setText("Num. Acciones: ");

        numAcciones.setText("0");

        jLabel2.setText("Valor Accion: ");

        valorAccion.setText("0.0");

        jLabel3.setText("Dinero:");

        dinero.setText("0");

        btnGraficas.setText("Graficas");
        btnGraficas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                graficas(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(valorAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGraficas))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numAcciones)
                    .addComponent(jLabel3)
                    .addComponent(dinero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGraficas)
                    .addComponent(valorAccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void graficas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficas


        ArrayList costeReal = new ArrayList();
        ArrayList costeHeuristico = new ArrayList();

        costeReal.add(new Integer(1));
        costeHeuristico.add(new Integer(2));
        costeReal.add(new Integer(2));
        costeHeuristico.add(new Integer(3));
        costeReal.add(new Integer(3));
        costeHeuristico.add(new Integer(4));

        //VentanaGraficas vGraficas = new VentanaGraficas(costeReal,costeHeuristico);

        ventana = VentanaGrafica.start(empresa,precio,volumen,fecha);
        ventana.setVisible(true);
    }//GEN-LAST:event_graficas


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficas;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel numAcciones;
    private javax.swing.JLabel valorAccion;
    // End of variables declaration//GEN-END:variables

    public void showValor(double valor){
        valorAccion.setText(String.valueOf(df.format(valor)));

        precio.add(new Double(String.valueOf(df.format(valor)).replaceAll(",", ".")));
        
    }

    public void showNumAcciones(long num){
        numAcciones.setText(String.valueOf(num));
    }

    public void showDinero(double dinero){
        this.dinero.setText(String.valueOf(df.format(dinero)));

        volumen.add(new Double(String.valueOf(df.format(dinero)).replaceAll(",", ".")));
        
    }

    public void addFecha(){
        fecha.add(new Date());
    }

    public void actualizar(){
        ventana.actualizar(precio,volumen,fecha);
    }
}
