/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BolsaAppGUI.java
 *
 * Created on 12-feb-2010, 1:49:30
 */

package ingenias.jade.components;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Victor
 */
public class AccionistaAppGUI extends javax.swing.JFrame {

    AccionistaAppAppImp accionista;
    DecimalFormat df = new DecimalFormat("0.0000");
    SimpleDateFormat sdt = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");

    /** Creates new form BolsaAppGUI */
    public AccionistaAppGUI() {
        initComponents();
    }

    AccionistaAppGUI(AccionistaAppAppImp accionista) {
        try { UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); }
        catch(Exception e){}

        initComponents();
        this.accionista = accionista;
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imgAccionista = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textDinero = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPaneles = new javax.swing.JTabbedPane();
        scrollLogPanel = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        btnInformacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accionista");

        jLabel1.setText("Agente Accionista");

        imgAccionista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        try{
            imgAccionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingenias/jade/components/accionista.jpg"))); // NOI18N
        }catch(Exception e){}
        imgAccionista.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Accionista"));

        estado.setText("Sin invertir");

        jLabel2.setText("Estado: ");

        jLabel3.setText("Dinero:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(textDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(190);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane2.setBorder(null);

        tablaPaneles.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresas Registradas"));
        tablaPaneles.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jScrollPane2.setViewportView(tablaPaneles);

        jSplitPane1.setTopComponent(jScrollPane2);

        scrollLogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));

        logArea.setColumns(20);
        logArea.setEditable(false);
        logArea.setRows(5);
        scrollLogPanel.setViewportView(logArea);

        jSplitPane1.setRightComponent(scrollLogPanel);

        btnInformacion.setText("Obtener Informacion");
        btnInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                obtenerInformacion(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnInformacion)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addComponent(imgAccionista)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgAccionista, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInformacion)
                .addGap(12, 12, 12)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerInformacion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obtenerInformacion
        accionista.obtenerInformacion();
    }//GEN-LAST:event_obtenerInformacion

    /**
    * @param args the command line arguments
    */
    public void start() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccionistaAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacion;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel imgAccionista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JScrollPane scrollLogPanel;
    private javax.swing.JTabbedPane tablaPaneles;
    private javax.swing.JTextField textDinero;
    // End of variables declaration//GEN-END:variables

    public void showLog(String cadena) {
       logArea.append(sdt.format(new Date())+ " " +cadena+"\n");
       scrollLogPanel.getVerticalScrollBar().setValue(scrollLogPanel.getVerticalScrollBar().getMaximum());
    }

    public void showInversiones(Vector<Inversion> inversiones) {

        InversionPanel panel;

        int indice = tablaPaneles.getSelectedIndex();

        tablaPaneles.removeAll();
        
        for(int i = 0; i<inversiones.size(); i++){
            
            panel = new InversionPanel(this);

            panel.setInversion(inversiones.get(i));
            
            tablaPaneles.addTab(inversiones.get(i).getEmpresa().getIdEmpresa(), panel);
        }

        if(indice!=-1)
            tablaPaneles.setSelectedIndex(indice);
        
    }

    void showEstado(String estado) {
        if(estado.equals("Compra realizada")){
            imgAccionista.setEnabled(true);
            this.estado.setText(estado);
        }else if(estado.startsWith("El numero")){
            this.estado.setText("Compra no efectuada");
            JOptionPane.showMessageDialog(this,
            estado,
            "Error Compra",
            JOptionPane.INFORMATION_MESSAGE);
        } else{
            this.estado.setText(estado);
        }


        
    }

    void showDinero(Double dinero) {
        this.textDinero.setText(String.valueOf(df.format(dinero)));
    }

    void comprar(long numeroAcciones) {

        InversionPanel panel = (InversionPanel) tablaPaneles.getSelectedComponent();
        Inversion inversion = panel.getInversion();
        String aux = textDinero.getText();
        aux = aux.replaceAll(",",".");

        double coste = (double)numeroAcciones * (double)inversion.getEmpresa().getValorAccion();
        double impuestos = (double)coste * (double)0.07;
        double costeReal = coste + impuestos;

        int value = JOptionPane.showConfirmDialog(null,
         "La operación de compra tiene un coste total de " + df.format(costeReal) + " euros." +
        "\n\n¿Desea continuar?","Confirmacion operación bursatil",
        JOptionPane.YES_NO_OPTION);

        if (value == JOptionPane.YES_OPTION) {

            double dinero = 0;
            try{
                dinero = Double.parseDouble(aux);
            }catch(Exception e){}

            if(costeReal>dinero){
                JOptionPane.showMessageDialog(this,
                "No dispones del dinero suficiente para comprar las acciones solicitadas.\n\n"+
                "Num. Acciones a comprar: " + numeroAcciones + "\n" +
                "Coste de las acciones: " + df.format(costeReal) + "\n" +
                "Dinero disponible: " + df.format(dinero)+ "\n" +
                "Dinero necesario: " + df.format(costeReal-dinero),
                "Dinero insuficiente",
                JOptionPane.WARNING_MESSAGE);

            }else{
                accionista.comprarAcciones(inversion.getEmpresa(),numeroAcciones,dinero,costeReal);
            }
        }
    }

    void vender(long numeroAcciones) {

        System.out.println("numeroAcciones: " +numeroAcciones);
        String aux = textDinero.getText();
        aux = aux.replaceAll(",",".");

        double dinero = 0;
        try{
            dinero = Double.parseDouble(aux);
        }catch(Exception e){}

        InversionPanel panel = (InversionPanel) tablaPaneles.getSelectedComponent();
        Inversion inversion = panel.getInversion();

        int value = JOptionPane.showConfirmDialog(null,
         "Se va a proceder a la venta de " + numeroAcciones + " acciones de " +inversion.getEmpresa().getIdEmpresa() +"." +
        "\n\n¿Desea continuar?","Confirmacion operación bursatil",
        JOptionPane.YES_NO_OPTION);

        if (value == JOptionPane.YES_OPTION)
            accionista.venderAcciones(inversion.getEmpresa(),dinero,numeroAcciones);

    }


}
