/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BolsaAppGUI.java
 *
 * Created on 12-feb-2010, 1:49:30
 */

package ingenias.jade.components;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.UIManager;

/**
 *
 * @author Victor
 */
public class BolsaAppGUI extends javax.swing.JFrame {

    BolsaAppAppImp bolsa;
    SimpleDateFormat sdt = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");

    /** Creates new form BolsaAppGUI */
    public BolsaAppGUI() {
        initComponents();
    }

    BolsaAppGUI(BolsaAppAppImp bolsa) {
        try { UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); }
        catch(Exception e){}

        initComponents();
        this.bolsa = bolsa;
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imgBolsa = new javax.swing.JLabel();
        tablaPaneles = new javax.swing.JTabbedPane();
        scrollLogPanel = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bolsa de Valores");

        jLabel1.setText("Agente Bolsa");

        imgBolsa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        try{
            imgBolsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingenias/jade/components/bolsa.jpg"))); // NOI18N
        }catch(Exception e){}
        imgBolsa.setEnabled(false);

        tablaPaneles.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresas Registradas"));

        scrollLogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));

        logArea.setColumns(20);
        logArea.setEditable(false);
        logArea.setRows(5);
        scrollLogPanel.setViewportView(logArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaPaneles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(imgBolsa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(scrollLogPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public void start() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BolsaAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBolsa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JScrollPane scrollLogPanel;
    private javax.swing.JTabbedPane tablaPaneles;
    // End of variables declaration//GEN-END:variables

    public void showLog(String cadena) {
       logArea.append(sdt.format(new Date())+ " " +cadena+"\n");
       scrollLogPanel.getVerticalScrollBar().setValue(scrollLogPanel.getVerticalScrollBar().getMaximum());
    }

    public void addEmpresa(Empresa empresa) {

        EmpresaPanel panel = new EmpresaPanel(empresa.getIdEmpresa());

        panel.showNumAcciones(empresa.getNumAcciones());
        panel.showValor(empresa.getValorAccion());
        panel.showDinero(empresa.getDinero());
        panel.addFecha();

        tablaPaneles.addTab(empresa.getIdEmpresa(), panel);

        imgBolsa.setEnabled(true);

    }

    public void actualizaEmpresa(Empresa empresa, int indice) {

        EmpresaPanel panel = (EmpresaPanel) tablaPaneles.getComponentAt(indice);

        panel.showNumAcciones(empresa.getNumAcciones());
        panel.showValor(empresa.getValorAccion());
        panel.showDinero(empresa.getDinero());
        panel.addFecha();
        panel.actualizar();
        
        tablaPaneles.setComponentAt(indice, panel);
    }
}
