/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmpresaPanel.java
 *
 * Created on 12-feb-2010, 2:19:53
 */

package ingenias.jade.components;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class InversionPanel extends javax.swing.JPanel {

    AccionistaAppGUI accionistaGUI;
    Inversion inversion;
    DecimalFormat df = new DecimalFormat("0.0000");

    /** Creates new form EmpresaPanel */
    public InversionPanel(AccionistaAppGUI accionistaGUI) {
        this.accionistaGUI = accionistaGUI;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numAcciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorAccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textComprar = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textVender = new javax.swing.JTextField();

        jLabel1.setText("Num. Acciones Compradas: ");

        numAcciones.setText("0");

        jLabel2.setText("Valor Accion: ");

        valorAccion.setText("0.0");

        jLabel3.setText("Num. Acciones a comprar: ");

        btnComprar.setText("Comprar");
        btnComprar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comprar(evt);
            }
        });

        btnVender.setText("Vender");
        btnVender.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vender(evt);
            }
        });

        jLabel4.setText("Num. Acciones a vender: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(numAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textVender, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numAcciones)
                    .addComponent(jLabel2)
                    .addComponent(valorAccion)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnComprar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnVender)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vender(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vender

        try{
            long numAccionesVender = Long.parseLong(textVender.getText());
            long numAccionesCompradas = Long.parseLong(numAcciones.getText());

            if(numAccionesCompradas-numAccionesVender<0){
                JOptionPane.showMessageDialog(this,
                "No dispones de tantas acciones para vender.\n\n"+
                "Num. máximo de acciones a vender: " + numAccionesCompradas,
                "Venta no efectuada",
                JOptionPane.INFORMATION_MESSAGE);
            }else{
                accionistaGUI.vender(numAccionesVender);
            }
            
        }catch(Exception e){

            JOptionPane.showMessageDialog(this,
            "Número de acciones a vender invalido.",
            "Error Venta",
            JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_vender

    private void comprar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprar
        try{
            long numeroAcciones = Long.parseLong(textComprar.getText());

            accionistaGUI.comprar(numeroAcciones);

        }catch(Exception e){

            JOptionPane.showMessageDialog(this,
            "Número de acciones a comprar invalido.",
            "Error Compra",
            JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_comprar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel numAcciones;
    private javax.swing.JTextField textComprar;
    private javax.swing.JTextField textVender;
    private javax.swing.JLabel valorAccion;
    // End of variables declaration//GEN-END:variables

    public void showValor(double valor){
        valorAccion.setText(String.valueOf(df.format(valor)));
    }

    public void showNumAcciones(long num){
        numAcciones.setText(String.valueOf(num));
    }

    public void setInversion(Inversion inversion) {

        this.inversion = inversion;

        showNumAcciones(inversion.getNumAccionesCompradas());
        showValor(inversion.getEmpresa().getValorAccion());

    }

    public Inversion getInversion() {

        return inversion;
    }


}
